Repository effortless-mgmt/EffortlessBackend, pull requests merged in 2018-11, with the labels that each got.

#27 Create Endpoint: Address
  EffortlessApi/Controllers/AddressController.cs
  EffortlessApi/Controllers/UserController.cs
  EffortlessApi/Models/Address.cs
  EffortlessApi/Models/Appointment.cs
  EffortlessApi/Models/Branch.cs
  EffortlessApi/Models/Company.cs
  EffortlessApi/Models/Job.cs
  EffortlessApi/Models/Privilege.cs
  EffortlessApi/Models/Role.cs
  EffortlessApi/Models/RolePrivilege.cs
  EffortlessApi/Models/TemporaryWorkPeriod.cs
  EffortlessApi/Models/User.cs
  EffortlessApi/Models/UserJobActive.cs
  EffortlessApi/Models/UserJobInactive.cs
  EffortlessApi/Models/UserTemporaryWorkPeriod.cs
  EffortlessApi/Models/WorkingHours.cs
Labels: feature

#33 Basic Authorization against db
  EffortlessApi/Controllers/AddressController.cs
  EffortlessApi/Controllers/AuthController.cs
  EffortlessApi/Controllers/UserController.cs
  EffortlessApi/Controllers/ValuesController.cs
  EffortlessApi/Core/IUnitOfWork.cs
  EffortlessApi/Core/Models/User.cs
  EffortlessApi/Core/Repositories/IRepository.cs
  EffortlessApi/Core/Repositories/IUserRepository.cs
  EffortlessApi/Extensions/ServiceExtensions.cs
  EffortlessApi/Migrations/20181108143504_add_all_models.Designer.cs
  EffortlessApi/Migrations/20181108143504_add_all_models.cs
  EffortlessApi/Migrations/EffortlessContextModelSnapshot.cs
  EffortlessApi/Persistence/Repositories/Repository.cs
  EffortlessApi/Persistence/Repositories/UserRepository.cs
  EffortlessApi/Persistence/UnitOfWork.cs
  EffortlessApi/Startup.cs
  docker-compose.yml
Labels: enhancement, feature

#45 Add roles from database as Role claim to JWT Token
  EffortlessApi/Controllers/AuthController.cs
  EffortlessApi/Controllers/UserController.cs
  EffortlessApi/Controllers/ValuesController.cs
  EffortlessApi/Persistence/Repositories/UserRepository.cs
Labels: bug, enhancement, review

#36 Privilege endpoint.
  EffortlessApi/Controllers/PrivilegeController.cs
  EffortlessApi/Core/IUnitOfWork.cs
  EffortlessApi/Core/Models/Privilege.cs
  EffortlessApi/Core/Models/Role.cs
  EffortlessApi/Core/Models/RolePrivilege.cs
  EffortlessApi/Core/Models/User.cs
  EffortlessApi/Core/Repositories/IPrivilegeRepository.cs
  EffortlessApi/Migrations/20180913142217_init.Designer.cs
  EffortlessApi/Migrations/20180913142217_init.cs
  EffortlessApi/Migrations/20180915135500_pw.Designer.cs
  EffortlessApi/Migrations/20180915135500_pw.cs
  EffortlessApi/Migrations/20181108143504_add_all_models.Designer.cs
  EffortlessApi/Migrations/20181114123453_FixUserRoleRelationship.cs
  EffortlessApi/Migrations/20181115095220_IAddedSomething.Designer.cs
  EffortlessApi/Migrations/20181115095220_IAddedSomething.cs
  EffortlessApi/Migrations/20181115142015_AllMigrations.Designer.cs
  EffortlessApi/Migrations/20181115142015_AllMigrations.cs
  EffortlessApi/Migrations/EffortlessContextModelSnapshot.cs
  EffortlessApi/Persistence/EffortlessContext.cs
  EffortlessApi/Persistence/EntityConfigurations/PrivilegeConfiguration.cs
  EffortlessApi/Persistence/EntityConfigurations/RolePrivilegeConfiguration.cs
  EffortlessApi/Persistence/Repositories/PrivilegeRepository.cs
  EffortlessApi/Persistence/Repositories/UserRepository.cs
  EffortlessApi/Persistence/UnitOfWork.cs
Labels: feature, new endpoint, question

#35 Address endpoint finished
  EffortlessApi/Controllers/AddressController.cs
  EffortlessApi/Controllers/UserController.cs
  EffortlessApi/Core/Repositories/IAddressRepository.cs
  EffortlessApi/Persistence/Repositories/AddressRepository.cs
Labels: enhancement

#38 Company endpoint.
  EffortlessApi/Controllers/CompanyController.cs
  EffortlessApi/Core/IUnitOfWork.cs
  EffortlessApi/Core/Repositories/ICompanyRepository.cs
  EffortlessApi/Persistence/Repositories/CompanyRepository.cs
  EffortlessApi/Persistence/UnitOfWork.cs
Labels: feature, new endpoint, question

#49 Fix spelling mistake: temorary->temporary
  EffortlessApi/Migrations/20181114152143_addJobToEffortlessContext.cs
  EffortlessApi/Migrations/20181115142015_AllMigrations.Designer.cs
  EffortlessApi/Migrations/20181115142015_AllMigrations.cs
  EffortlessApi/Migrations/20181117191432_RemoveCompanyToUser.Designer.cs
  EffortlessApi/Migrations/20181117191526_RefactorRoadToStreet.Designer.cs
  EffortlessApi/Migrations/20181117191839_AddStateRemoveReq.Designer.cs
  EffortlessApi/Migrations/20181118160003_ImplementedAllModels.Designer.cs
  EffortlessApi/Migrations/20181118160003_ImplementedAllModels.cs
  EffortlessApi/Migrations/EffortlessContextModelSnapshot.cs
  EffortlessApi/Persistence/EffortlessContext.cs
Labels: bug

#55 Add role to user
  EffortlessApi/Controllers/RoleController.cs
  EffortlessApi/Controllers/UserController.cs
  EffortlessApi/Core/Models/User.cs
Labels: feature

#62 Reset migrations script and addition to gitignore and readme
  .gitignore
  readme.md
  resetMigration.sh
Labels: enhancement, review
