Repository effortless-mgmt/EffortlessBackend, pull requests merged in 2018-12, with the labels that each got.

#65 Fix globalization of JWT signing key
  EffortlessApi/Controllers/AuthController.cs
  EffortlessApi/Core/IJwtSettings.cs
  EffortlessApi/Core/JwtSettings.cs
  EffortlessApi/Extensions/ServiceExtensions.cs
  EffortlessApi/Startup.cs
Labels: bug, enhancement, review

#71 Split names in UserDTO into Firstname and Lastname
  EffortlessLibrary/DTO/User/UserSimpleDTO.cs
  EffortlessLibrary/DTO/User/UserStrippedDTO.cs
Labels: bug

#72 Feature/fix user and department endpoints
  EffortlessApi/Controllers/DepartmentController.cs
  EffortlessApi/Controllers/UserController.cs
  EffortlessApi/Core/Repositories/IAppointmentRepository.cs
  EffortlessApi/Core/Repositories/IUserWorkPeriodRepository.cs
  EffortlessApi/Core/Repositories/IWorkPeriodRepository.cs
  EffortlessApi/Mapper/MappingProfile.cs
  EffortlessApi/Persistence/Repositories/AppointmentRepository.cs
  EffortlessApi/Persistence/Repositories/Repository.cs
  EffortlessApi/Persistence/Repositories/UserWorkPeriodRepository.cs
  EffortlessApi/Persistence/Repositories/WorkPeriodRepository.cs
  EffortlessLibrary/DTO/Appointment/AppointmentUserDTO.cs
  EffortlessLibrary/DTO/WorkPeriod/WorkPeriodUserAppointmentDTO.cs
Labels: enhancement

#75 Adding endpoint filtering and small fixes
  EffortlessApi/Controllers/RoleController.cs
  EffortlessApi/Controllers/UserController.cs
  EffortlessApi/Core/Repositories/IUserRoleRepository.cs
  EffortlessApi/Core/Repositories/IUserWorkPeriodRepository.cs
  start-docker.sh
Labels: bug, enhancement

#77 Work period should return a larger user
  EffortlessApi/Controllers/DepartmentController.cs
  EffortlessApi/Controllers/WorkPeriodController.cs
  EffortlessLibrary/DTO/Appointment/AppointmentWpDTO.cs
  EffortlessLibrary/DTO/PivotTables/UserWorkPeriodDTO.cs
  EffortlessLibrary/DTO/WorkPeriod/WorkPeriodOutDTO.cs
Labels: enhancement
